### PR TITLE
 save_train_forecasts with already trained model 

### PR DESCRIPTION
**Pull request by BenoitHardier**
…aframe to manage save_train_forecasts

Signed-off-by: Benoit Hardier <benoit.hardier@probayes.com>

### CODE REVIEW

**Comment by BenoitHardier** [comment]
I managed to do it with an exception. Could you look at it @JanMaartenvanDoorn ?

**Review by JanMaartenvanDoorn — APPROVED** [review]
Looks good, this exception makes more clear what is happening.

**Comment by JanMaartenvanDoorn** [comment]
I just had a look, seems the build succeeded: https://github.com/OpenSTEF/openstef/actions/runs/3408913699 , are you ready to merge? If so I will merge it.

**Comment by BenoitHardier** [comment]
Hi @JanMaartenvanDoorn, yes you can merge it.

**Pull request merged**
